{***************************************************************}
{ FIBPlus - component library for direct access to Firebird and }
{ InterBase databases                                           }
{                                                               }
{    FIBPlus is based in part on the product                    }
{    Free IB Components, written by Gregory H. Deatz for        }
{    Hoagland, Longo, Moran, Dunst & Doukas Company.            }
{    mailto:gdeatz@hlmdd.com                                    }
{                                                               }
{    Copyright (c) 1998-2013 Devrace Ltd.                       }
{    Written by Serge Buzadzhy                                  }
{                                                               }
{  Please see the file License.txt for full license information }
{***************************************************************}
  FIBMajorVersion: Integer = 7;
  FIBMinorVersion: Integer = 9;
  FIBRelease: Integer      = 0;
  FIBBuildDate             = '01.10.2026';
  FIBVersionNote           = 'Release';
  FIBPalette               = 'FIBPlus';
  


